/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditProfilePage.java
 *
 * Created on Nov 17, 2009, 9:41:25 PM
 */

/**
 *
 * @author 17thkent
 */
import javax.swing.*;
import java.awt.*;
import javax.swing.ImageIcon;

public class EditProfilePage extends javax.swing.JFrame {

    /** Creates new form EditProfilePage */
    private Member currentMember;
    private Database db = new Database();
    private LogFile file;
    private ImageIcon img;
    public EditProfilePage(Member m) {
        currentMember = m;
        img = new ImageIcon(this.getClass().getResource("images/SMD_Library_Background.jpg"));
        file = new LogFile();
        initComponents();
        setBackground();
        jlbID.setText("ID: "+currentMember.getID());
        jtfFirstName.setText(m.getFirstName());
        jtfLastName.setText(m.getLastName());
        jtfPhoneNo.setText(m.getPhone());
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnOuter = new javax.swing.JPanel()
        {
            protected void paintComponent(Graphics g){
                //  Scale image to size of component
                Dimension d = getSize();
                g.drawImage(img.getImage(), 0, 0, d.width, d.height, null);
                super.paintComponent(g);
            }
        }
        ;
        jtfLastName = new javax.swing.JTextField();
        jtfFirstName = new javax.swing.JTextField();
        jlblPhone = new javax.swing.JLabel();
        jlblOldPassword = new javax.swing.JLabel();
        jlbID = new javax.swing.JLabel();
        jlblLName = new javax.swing.JLabel();
        jlblFName = new javax.swing.JLabel();
        jtfAnswer = new javax.swing.JTextField();
        jlblAnswer = new javax.swing.JLabel();
        jcbQuestion = new javax.swing.JComboBox();
        jlblQuestion = new javax.swing.JLabel();
        jlblNewPassword = new javax.swing.JLabel();
        jlblConfirm = new javax.swing.JLabel();
        jpfConfirmPassword = new javax.swing.JPasswordField();
        jpfNewPassword = new javax.swing.JPasswordField();
        jpfOldPassword = new javax.swing.JPasswordField();
        jbtBack = new javax.swing.JButton();
        jtfPhoneNo = new javax.swing.JTextField();
        jbtReset = new javax.swing.JButton();
        jbtSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Profile");
        setIconImage(new ImageIcon(getClass().getResource("images/HomeIcon.png")).getImage());
        setResizable(false);

        jtfLastName.setBackground(new java.awt.Color(255, 255, 0));

        jtfFirstName.setBackground(new java.awt.Color(255, 255, 0));

        jlblPhone.setText("Phone Number");

        jlblOldPassword.setText("Old Password");

        jlbID.setFont(new java.awt.Font("Arial", 1, 14));
        jlbID.setText("ID:");

        jlblLName.setText("Last Name");

        jlblFName.setText("First Name");

        jtfAnswer.setText("Please enter your answer here");
        jtfAnswer.setToolTipText("Answer not more than 15 character");
        jtfAnswer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfAnswerMouseClicked(evt);
            }
        });
        jtfAnswer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfAnswerFocusLost(evt);
            }
        });

        jlblAnswer.setText("Answer");

        jcbQuestion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "What is your father's name?", "What is your mother's name?", "What is your favourite food?", "Where is your hometown?", "What is your secondary school's name?" }));
        jcbQuestion.setToolTipText("Enable you to trace back the password when you forgot the password");

        jlblQuestion.setText("Question");

        jlblNewPassword.setText("New Password");

        jlblConfirm.setText("Confirm Password");

        jpfConfirmPassword.setBackground(new java.awt.Color(255, 255, 0));

        jpfNewPassword.setBackground(new java.awt.Color(255, 255, 0));
        jpfNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpfNewPasswordActionPerformed(evt);
            }
        });

        jpfOldPassword.setBackground(new java.awt.Color(255, 255, 0));

        jbtBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/240.png"))); // NOI18N
        jbtBack.setMnemonic('B');
        jbtBack.setText("Back To Main Page");
        jbtBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBackActionPerformed(evt);
            }
        });

        jbtReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_reset.png"))); // NOI18N
        jbtReset.setMnemonic('R');
        jbtReset.setText("Reset to default");
        jbtReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtResetActionPerformed(evt);
            }
        });

        jbtSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/260.png"))); // NOI18N
        jbtSubmit.setMnemonic('S');
        jbtSubmit.setText("Submit");
        jbtSubmit.setToolTipText("Yellow field cannot be blank");
        jbtSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnOuterLayout = new javax.swing.GroupLayout(jpnOuter);
        jpnOuter.setLayout(jpnOuterLayout);
        jpnOuterLayout.setHorizontalGroup(
            jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnOuterLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnOuterLayout.createSequentialGroup()
                        .addComponent(jbtSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtReset, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtBack, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                        .addGap(53, 53, 53))
                    .addGroup(jpnOuterLayout.createSequentialGroup()
                        .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnOuterLayout.createSequentialGroup()
                                .addComponent(jlbID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnOuterLayout.createSequentialGroup()
                                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblFName, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblLName, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jtfFirstName, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtfLastName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlblConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlblOldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlblNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jpfNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jpfOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jpfConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(49, 49, 49))
                    .addGroup(jpnOuterLayout.createSequentialGroup()
                        .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnOuterLayout.createSequentialGroup()
                                .addComponent(jlblAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfAnswer))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnOuterLayout.createSequentialGroup()
                                .addComponent(jlblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jcbQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(263, 263, 263))))
        );
        jpnOuterLayout.setVerticalGroup(
            jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnOuterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbID)
                .addGap(18, 18, 18)
                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnOuterLayout.createSequentialGroup()
                        .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblFName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblLName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jpfConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnOuterLayout.createSequentialGroup()
                                .addComponent(jlblOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlblNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jpfNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlblConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jpfOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblQuestion)
                    .addComponent(jcbQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSubmit)
                    .addComponent(jbtReset)
                    .addComponent(jbtBack))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnOuter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnOuter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSubmitActionPerformed
        // TODO add your handling code here:
        Member mem = new Member();
        Object options[] = {"Confirm","Cancel"};
        String oldPassword = getStringPassword(jpfOldPassword.getPassword());
        String newPassword = getStringPassword(jpfNewPassword.getPassword());
        String confirmPassword = getStringPassword(jpfConfirmPassword.getPassword());
        String msg = "";
        if(jtfFirstName.getText().equals("") || jtfLastName.getText().equals("") || oldPassword.equals("") ||
            newPassword.equals("") || confirmPassword.equals(""))
        {
            JOptionPane.showMessageDialog(null,"Incomplete Information!","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else if(!oldPassword.equals(currentMember.getPassword()))
            JOptionPane.showMessageDialog(null,"Old Password does not match! Please re-enter...","Invalid password",JOptionPane.ERROR_MESSAGE);
        else if(!newPassword.equals(confirmPassword))
            JOptionPane.showMessageDialog(null,"New Password does not match with Confirm Password! Please re-enter...","Invalid password",JOptionPane.ERROR_MESSAGE);
        else{
            try{
                mem.setID(currentMember.getID());
                mem.setPassword(newPassword);
                mem.setFirstName(jtfFirstName.getText());
                mem.setLastName(jtfLastName.getText());
                msg += "First Name: "+mem.getFirstName() +
                       "\nLast Name: "+mem.getLastName();

                if(!jtfPhoneNo.getText().equals("")){
                    if(jtfPhoneNo.getText().length()>=9 && jtfPhoneNo.getText().length()<=12){
                        Long.parseLong(jtfPhoneNo.getText());
                        mem.setPhone(jtfPhoneNo.getText());
                        msg += "\nPhone no.: "+mem.getPhone();
               
                        if(jtfAnswer.getText().equals("Please enter your answer here"))
                        {
                            mem.setAnswer("");
                            mem.setQuestion("");
                        }
                        else if(jtfAnswer.getText().equals(""))
                            JOptionPane.showMessageDialog(null,"Please enter your answer according to your question","Security answer",JOptionPane.WARNING_MESSAGE);
                        else{
                            mem.setQuestion((String)jcbQuestion.getSelectedItem());
                            mem.setAnswer(jtfAnswer.getText());
                            msg +=  "\nQuestion: "+mem.getQuestion()+"\nAnswer: "+mem.getAnswer();
                        }
                        int x = JOptionPane.showOptionDialog(null, msg, "Confirm?",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE, null, options,options[0]);

                        if(x == JOptionPane.YES_OPTION)
                        {
                            mem = db.editProfile(mem);
                            msg = "ID: "+mem.getID()+
                                   "\nName: "+mem.getFirstName()+" "+mem.getLastName()+
                                   "\nIC: "+mem.getIC()+
                                   "\nGender: "+mem.getGender();
                            if(!mem.getPhone().equals(""))
                                msg += "\nPhone no.: "+mem.getPhone();
                            if(!mem.getQuestion().equals(""))
                            {
                                msg += "\nQuestion: "+mem.getQuestion()+
                                        "\nAnswer: "+mem.getAnswer();
                            }
                            msg += "\nBalance: "+String.format("RM %.2f",mem.getBalance());
                            JOptionPane.showMessageDialog(null,"Your profile have been changed\n"+msg);
                            new UserPage(mem).setVisible(true);
                            this.dispose();
                        }
                        else
                            JOptionPane.showMessageDialog(null,"You have been cancelled editing profile!","Edit cancelled",JOptionPane.PLAIN_MESSAGE);
                            }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"Phone no. should be in 9 - 12 digits!","Phone number out of range",JOptionPane.WARNING_MESSAGE);

                    }
                }
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Phone number should only contain digits!","Invalid Input!",JOptionPane.ERROR_MESSAGE);
                file.exceptionRecord(e.getStackTrace());
            }
            catch(NameFormatException e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage(),"Invalid Input!",JOptionPane.ERROR_MESSAGE);
                file.exceptionRecord(e.getStackTrace());
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
                file.exceptionRecord(e.getStackTrace());
            }
        }
    }//GEN-LAST:event_jbtSubmitActionPerformed

    private void jtfAnswerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfAnswerMouseClicked
        // TODO add your handling code here:
        if(jtfAnswer.getText().equalsIgnoreCase("Please enter your answer here"))
            jtfAnswer.setText("");
}//GEN-LAST:event_jtfAnswerMouseClicked

    private void jtfAnswerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfAnswerFocusLost
        // TODO add your handling code here:
        if(jtfAnswer.getText().equalsIgnoreCase(""))
            jtfAnswer.setText("Please enter your answer here");
}//GEN-LAST:event_jtfAnswerFocusLost

    private void jpfNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfNewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpfNewPasswordActionPerformed

    private void jbtBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBackActionPerformed
        // TODO add your handling code here:
        new UserPage(currentMember).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtBackActionPerformed

    private void jbtResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtResetActionPerformed
        // TODO add your handling code here:
        jtfFirstName.setText(currentMember.getFirstName());
        jtfLastName.setText(currentMember.getLastName());
        jtfPhoneNo.setText(currentMember.getPhone()+"");
        jpfOldPassword.setText("");
        jpfNewPassword.setText("");
        jpfConfirmPassword.setText("");
        jtfAnswer.setText("Please enter your answer here");
    }//GEN-LAST:event_jbtResetActionPerformed

  private void setBackground()
  {
          java.net.URL url = this.getClass().getResource("images/SMD_Library_Background.jpg");
          ImageIcon imageBack = new ImageIcon(url);
          JLabel jlbBackground = new JLabel(imageBack);
          jlbBackground.setBounds(0, 0, imageBack.getIconWidth(),imageBack.getIconWidth());
          getLayeredPane().add(jlbBackground, new Integer(Integer.MIN_VALUE));
          jpnOuter.setOpaque(false);
          setContentPane(jpnOuter);
  }
    /**
    * @param args the command line arguments
    */

    private String getStringPassword(char[] pw)
    {
        String password = "";
        for(int i=0;i<pw.length;i++)
        {
            password += pw[i];
        }
        return password;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtBack;
    private javax.swing.JButton jbtReset;
    private javax.swing.JButton jbtSubmit;
    private javax.swing.JComboBox jcbQuestion;
    private javax.swing.JLabel jlbID;
    private javax.swing.JLabel jlblAnswer;
    private javax.swing.JLabel jlblConfirm;
    private javax.swing.JLabel jlblFName;
    private javax.swing.JLabel jlblLName;
    private javax.swing.JLabel jlblNewPassword;
    private javax.swing.JLabel jlblOldPassword;
    private javax.swing.JLabel jlblPhone;
    private javax.swing.JLabel jlblQuestion;
    private javax.swing.JPasswordField jpfConfirmPassword;
    private javax.swing.JPasswordField jpfNewPassword;
    private javax.swing.JPasswordField jpfOldPassword;
    private javax.swing.JPanel jpnOuter;
    private javax.swing.JTextField jtfAnswer;
    private javax.swing.JTextField jtfFirstName;
    private javax.swing.JTextField jtfLastName;
    private javax.swing.JTextField jtfPhoneNo;
    // End of variables declaration//GEN-END:variables

}
