/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ForgotPasswordPage.java
 *
 * Created on Nov 14, 2009, 10:45:37 AM
 */

/**
 *
 * @author Js Lim
 */
import javax.swing.*;
import java.awt.*;
import javax.swing.ImageIcon;

public class ForgotPasswordPage extends javax.swing.JFrame {

    Database db = new Database();
    private ImageIcon img;

    /** Creates new form ForgotPasswordPage */
    public ForgotPasswordPage() {
        img = new ImageIcon(this.getClass().getResource("images/SMD_Library_Background.jpg"));
        initComponents();
        setBackground();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnOuter = new javax.swing.JPanel()
        {
            protected void paintComponent(Graphics g){
                //  Scale image to size of component
                Dimension d = getSize();
                g.drawImage(img.getImage(), 0, 0, d.width, d.height, null);
                super.paintComponent(g);
            }
        }
        ;
        jcbQuestion = new javax.swing.JComboBox();
        jtfAnswer = new javax.swing.JTextField();
        jbtOk = new javax.swing.JButton();
        jlbQuestion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jbtBack = new javax.swing.JButton();
        jtfMemberID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Forgot Password?");
        setIconImage(new ImageIcon(getClass().getResource("images/HomeIcon.png")).getImage());
        setResizable(false);

        jcbQuestion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "What is your father's name?", "What is your mother's name?", "What is your favourite food?", "Where is your hometown?", "What is your secondary school's name?" }));
        jcbQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbQuestionActionPerformed(evt);
            }
        });

        jbtOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ok-128.png"))); // NOI18N
        jbtOk.setMnemonic('O');
        jbtOk.setText("Ok");
        jbtOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOkActionPerformed(evt);
            }
        });

        jlbQuestion.setText("Question");

        jLabel1.setText("Answer");

        jbtBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BackButton.png"))); // NOI18N
        jbtBack.setMnemonic('B');
        jbtBack.setText("Back");
        jbtBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBackActionPerformed(evt);
            }
        });

        jLabel2.setText("Please enter your ID:");

        javax.swing.GroupLayout jpnOuterLayout = new javax.swing.GroupLayout(jpnOuter);
        jpnOuter.setLayout(jpnOuterLayout);
        jpnOuterLayout.setHorizontalGroup(
            jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnOuterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnOuterLayout.createSequentialGroup()
                        .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnOuterLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnOuterLayout.createSequentialGroup()
                                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jlbQuestion))
                                .addGap(23, 23, 23)
                                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfAnswer)
                                    .addComponent(jcbQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jpnOuterLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jbtOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(jbtBack)
                        .addGap(50, 50, 50))))
        );
        jpnOuterLayout.setVerticalGroup(
            jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnOuterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbQuestion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtOk)
                    .addComponent(jbtBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnOuter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnOuter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOkActionPerformed
        // TODO add your handling code here:
        String password = "";
        if(jtfMemberID.getText().equals("") || jtfAnswer.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Incomplete information!","Incomplete information",JOptionPane.ERROR_MESSAGE);
        else{
            password = db.retrievePassword(jtfMemberID.getText(),(String)jcbQuestion.getSelectedItem(),jtfAnswer.getText());

            if(password.equals(""))
                JOptionPane.showMessageDialog(null,"Question & Answer does not match!","Choose a question",JOptionPane.ERROR_MESSAGE);
            else{
                JOptionPane.showMessageDialog(null,"Your password is <"+password+"> !","Retrieve password successful",JOptionPane.INFORMATION_MESSAGE);
                new LoginPage().setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jbtOkActionPerformed

    private void jbtBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBackActionPerformed
        // TODO add your handling code here:
       new LoginPage().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jbtBackActionPerformed

    private void jcbQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbQuestionActionPerformed

  private void setBackground()
  {
          java.net.URL url = this.getClass().getResource("images/SMD_Library_Background.jpg");
          ImageIcon imageBack = new ImageIcon(url);
          JLabel jlbBackground = new JLabel(imageBack);
          jlbBackground.setBounds(0, 0, imageBack.getIconWidth(),imageBack.getIconHeight());
          getLayeredPane().add(jlbBackground, new Integer(Integer.MIN_VALUE));
          jpnOuter.setOpaque(false);
          setContentPane(jpnOuter);
  }
    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtBack;
    private javax.swing.JButton jbtOk;
    private javax.swing.JComboBox jcbQuestion;
    private javax.swing.JLabel jlbQuestion;
    private javax.swing.JPanel jpnOuter;
    private javax.swing.JTextField jtfAnswer;
    private javax.swing.JTextField jtfMemberID;
    // End of variables declaration//GEN-END:variables

}
