/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RentReport.java
 *
 * Created on Dec 2, 2009, 3:41:15 PM
 */

/**
 *
 * @author Js Lim
 */
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import java.awt.*;
import javax.swing.ImageIcon;

public class RentReport extends javax.swing.JFrame {

    final static int MONTH_OF_YEAR = 12;
    private double subTotal[] = new double[MONTH_OF_YEAR];
    private int subCount[] = new int[MONTH_OF_YEAR];
    private double total = 0.0;
    private int count = 0;
    private Database db;
    private javax.swing.ImageIcon img;
    private Staff adm;
    private int year;

    /** Creates new form RentReport */
    public RentReport(Staff adm,int year) {
        this.adm = adm;
        this.year = year;
        try{
            img = new javax.swing.ImageIcon(this.getClass().getResource("images/SMD_Library_Background.jpg"));
            db = new Database();
            subTotal = db.getTotalRent(year);
            subCount = db.getTotalCount(year);
            for(int i=0;i<MONTH_OF_YEAR;i++)
            {
                total += subTotal[i];
                count += subCount[i];
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Exception: "+e.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
            new LogFile().exceptionRecord(e.getStackTrace());
            e.printStackTrace();
        }
        initComponents();
        setBackground();
        setLocationRelativeTo(null);
        jtfTitle.setText("YEAR "+year+" SALES REPORT");
            jlbBookCount1.setText(subCount[0]+"");
            jlbBookCount2.setText(subCount[1]+"");
            jlbBookCount3.setText(subCount[2]+"");
            jlbBookCount4.setText(subCount[3]+"");
            jlbBookCount5.setText(subCount[4]+"");
            jlbBookCount6.setText(subCount[5]+"");
            jlbBookCount7.setText(subCount[6]+"");
            jlbBookCount8.setText(subCount[7]+"");
            jlbBookCount9.setText(subCount[8]+"");
            jlbBookCount10.setText(subCount[9]+"");
            jlbBookCount11.setText(subCount[10]+"");
            jlbBookCount12.setText(subCount[11]+"");
            jlbRevenue1.setText(String.format("%.2f",subTotal[0]));
            jlbRevenue2.setText(String.format("%.2f",subTotal[1]));
            jlbRevenue3.setText(String.format("%.2f",subTotal[2]));
            jlbRevenue4.setText(String.format("%.2f",subTotal[3]));
            jlbRevenue5.setText(String.format("%.2f",subTotal[4]));
            jlbRevenue6.setText(String.format("%.2f",subTotal[5]));
            jlbRevenue7.setText(String.format("%.2f",subTotal[6]));
            jlbRevenue8.setText(String.format("%.2f",subTotal[7]));
            jlbRevenue9.setText(String.format("%.2f",subTotal[8]));
            jlbRevenue10.setText(String.format("%.2f",subTotal[9]));
            jlbRevenue11.setText(String.format("%.2f",subTotal[10]));
            jlbRevenue12.setText(String.format("%.2f",subTotal[11]));
            jlbTotalCount.setText(count+"");
            jlbTotalRent.setText(String.format("%.2f",total));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnOuter = new javax.swing.JPanel()
        {
            protected void paintComponent(Graphics g){
                //  Scale image to size of component
                Dimension d = getSize();
                g.drawImage(img.getImage(), 0, 0, d.width, d.height, null);
                super.paintComponent(g);
            }
        }
        ;
        jtfTitle = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jlbBookCount1 = new javax.swing.JLabel();
        jlbBookCount2 = new javax.swing.JLabel();
        jlbBookCount3 = new javax.swing.JLabel();
        jlbBookCount4 = new javax.swing.JLabel();
        jlbBookCount5 = new javax.swing.JLabel();
        jlbBookCount6 = new javax.swing.JLabel();
        jlbBookCount7 = new javax.swing.JLabel();
        jlbBookCount8 = new javax.swing.JLabel();
        jlbBookCount9 = new javax.swing.JLabel();
        jlbBookCount10 = new javax.swing.JLabel();
        jlbBookCount11 = new javax.swing.JLabel();
        jlbBookCount12 = new javax.swing.JLabel();
        jlbRevenue3 = new javax.swing.JLabel();
        jlbRevenue2 = new javax.swing.JLabel();
        jlbRevenue7 = new javax.swing.JLabel();
        jlbRevenue6 = new javax.swing.JLabel();
        jlbRevenue5 = new javax.swing.JLabel();
        jlbRevenue4 = new javax.swing.JLabel();
        jlbRevenue12 = new javax.swing.JLabel();
        jlbRevenue11 = new javax.swing.JLabel();
        jlbRevenue9 = new javax.swing.JLabel();
        jlbRevenue8 = new javax.swing.JLabel();
        jlbRevenue10 = new javax.swing.JLabel();
        jlbRevenue1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jlbTotalCount = new javax.swing.JLabel();
        jlbTotalRent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SMD Library Monthly Sales Report");
        setIconImage(new ImageIcon(getClass().getResource("images/HomeIcon.png")).getImage());
        setResizable(false);

        jpnOuter.setToolTipText("Click anywhere to close");
        jpnOuter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnOuterMouseClicked(evt);
            }
        });

        jtfTitle.setEditable(false);
        jtfTitle.setFont(new java.awt.Font("Arial", 1, 24));
        jtfTitle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfTitle.setText("Year 2009 Sales Report");
        jtfTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtfTitle.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfTitle.setEnabled(false);
        jtfTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTitleActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel1.setText("April");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel2.setText("February");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel4.setText("December");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel5.setText("March");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel6.setText("May");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel7.setText("July");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel8.setText("June");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel9.setText("August");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel10.setText("September");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel11.setText("October");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel12.setText("November");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel3.setText("January");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 20));
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("MONTH");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 20));
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("TOTAL RENTED BOOK");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 20));
        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setText("TOTAL REVENUE (RM)");

        jlbBookCount1.setFont(new java.awt.Font("Arial", 0, 18));
        jlbBookCount1.setForeground(new java.awt.Color(255, 0, 0));
        jlbBookCount1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbBookCount1.setText(" ");

        jlbBookCount2.setFont(new java.awt.Font("Arial", 0, 18));
        jlbBookCount2.setForeground(new java.awt.Color(255, 0, 0));
        jlbBookCount2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbBookCount2.setText(" ");

        jlbBookCount3.setFont(new java.awt.Font("Arial", 0, 18));
        jlbBookCount3.setForeground(new java.awt.Color(255, 0, 0));
        jlbBookCount3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbBookCount3.setText(" ");

        jlbBookCount4.setFont(new java.awt.Font("Arial", 0, 18));
        jlbBookCount4.setForeground(new java.awt.Color(255, 0, 0));
        jlbBookCount4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbBookCount4.setText(" ");

        jlbBookCount5.setFont(new java.awt.Font("Arial", 0, 18));
        jlbBookCount5.setForeground(new java.awt.Color(255, 0, 0));
        jlbBookCount5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbBookCount5.setText(" ");

        jlbBookCount6.setFont(new java.awt.Font("Arial", 0, 18));
        jlbBookCount6.setForeground(new java.awt.Color(255, 0, 0));
        jlbBookCount6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbBookCount6.setText(" ");

        jlbBookCount7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlbBookCount7.setForeground(new java.awt.Color(255, 0, 0));
        jlbBookCount7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbBookCount7.setText(" ");

        jlbBookCount8.setFont(new java.awt.Font("Arial", 0, 18));
        jlbBookCount8.setForeground(new java.awt.Color(255, 0, 0));
        jlbBookCount8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbBookCount8.setText(" ");

        jlbBookCount9.setFont(new java.awt.Font("Arial", 0, 18));
        jlbBookCount9.setForeground(new java.awt.Color(255, 0, 0));
        jlbBookCount9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbBookCount9.setText(" ");

        jlbBookCount10.setFont(new java.awt.Font("Arial", 0, 18));
        jlbBookCount10.setForeground(new java.awt.Color(255, 0, 0));
        jlbBookCount10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbBookCount10.setText(" ");

        jlbBookCount11.setFont(new java.awt.Font("Arial", 0, 18));
        jlbBookCount11.setForeground(new java.awt.Color(255, 0, 0));
        jlbBookCount11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbBookCount11.setText(" ");

        jlbBookCount12.setFont(new java.awt.Font("Arial", 0, 18));
        jlbBookCount12.setForeground(new java.awt.Color(255, 0, 0));
        jlbBookCount12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbBookCount12.setText(" ");

        jlbRevenue3.setFont(new java.awt.Font("Arial", 0, 18));
        jlbRevenue3.setForeground(new java.awt.Color(255, 0, 0));
        jlbRevenue3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbRevenue3.setText(" ");

        jlbRevenue2.setFont(new java.awt.Font("Arial", 0, 18));
        jlbRevenue2.setForeground(new java.awt.Color(255, 0, 0));
        jlbRevenue2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbRevenue2.setText(" ");

        jlbRevenue7.setFont(new java.awt.Font("Arial", 0, 18));
        jlbRevenue7.setForeground(new java.awt.Color(255, 0, 0));
        jlbRevenue7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbRevenue7.setText(" ");

        jlbRevenue6.setFont(new java.awt.Font("Arial", 0, 18));
        jlbRevenue6.setForeground(new java.awt.Color(255, 0, 0));
        jlbRevenue6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbRevenue6.setText(" ");

        jlbRevenue5.setFont(new java.awt.Font("Arial", 0, 18));
        jlbRevenue5.setForeground(new java.awt.Color(255, 0, 0));
        jlbRevenue5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbRevenue5.setText(" ");

        jlbRevenue4.setFont(new java.awt.Font("Arial", 0, 18));
        jlbRevenue4.setForeground(new java.awt.Color(255, 0, 0));
        jlbRevenue4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbRevenue4.setText(" ");

        jlbRevenue12.setFont(new java.awt.Font("Arial", 0, 18));
        jlbRevenue12.setForeground(new java.awt.Color(255, 0, 0));
        jlbRevenue12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbRevenue12.setText(" ");

        jlbRevenue11.setFont(new java.awt.Font("Arial", 0, 18));
        jlbRevenue11.setForeground(new java.awt.Color(255, 0, 0));
        jlbRevenue11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbRevenue11.setText(" ");

        jlbRevenue9.setFont(new java.awt.Font("Arial", 0, 18));
        jlbRevenue9.setForeground(new java.awt.Color(255, 0, 0));
        jlbRevenue9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbRevenue9.setText(" ");

        jlbRevenue8.setFont(new java.awt.Font("Arial", 0, 18));
        jlbRevenue8.setForeground(new java.awt.Color(255, 0, 0));
        jlbRevenue8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbRevenue8.setText(" ");

        jlbRevenue10.setFont(new java.awt.Font("Arial", 0, 18));
        jlbRevenue10.setForeground(new java.awt.Color(255, 0, 0));
        jlbRevenue10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbRevenue10.setText(" ");

        jlbRevenue1.setFont(new java.awt.Font("Arial", 0, 18));
        jlbRevenue1.setForeground(new java.awt.Color(255, 0, 0));
        jlbRevenue1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbRevenue1.setText(" ");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setText("TOTAL");

        jlbTotalCount.setFont(new java.awt.Font("Arial", 1, 18));
        jlbTotalCount.setForeground(new java.awt.Color(255, 0, 0));
        jlbTotalCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTotalCount.setText(" ");

        jlbTotalRent.setFont(new java.awt.Font("Arial", 1, 18));
        jlbTotalRent.setForeground(new java.awt.Color(255, 0, 0));
        jlbTotalRent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTotalRent.setText(" ");

        javax.swing.GroupLayout jpnOuterLayout = new javax.swing.GroupLayout(jpnOuter);
        jpnOuter.setLayout(jpnOuterLayout);
        jpnOuterLayout.setHorizontalGroup(
            jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnOuterLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                    .addGroup(jpnOuterLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnOuterLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(56, 56, 56)
                                .addComponent(jLabel15)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnOuterLayout.createSequentialGroup()
                                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlbBookCount2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbBookCount1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbBookCount3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbBookCount4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbBookCount5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbBookCount6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbBookCount7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbBookCount8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbBookCount9, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbBookCount10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbBookCount11, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbBookCount12, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbTotalCount, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(144, 144, 144)
                                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlbRevenue2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbRevenue1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbRevenue3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbRevenue4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbRevenue6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbRevenue7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbRevenue8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbRevenue9, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbRevenue10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbRevenue11, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbRevenue12, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbRevenue5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbTotalRent, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(79, 79, 79)))))
                .addGap(20, 20, 20))
        );
        jpnOuterLayout.setVerticalGroup(
            jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnOuterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnOuterLayout.createSequentialGroup()
                        .addComponent(jlbRevenue1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlbRevenue2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlbRevenue3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlbRevenue4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlbRevenue5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlbRevenue6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlbRevenue7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlbRevenue8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlbRevenue9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlbRevenue10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlbRevenue11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlbRevenue12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlbTotalRent, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnOuterLayout.createSequentialGroup()
                        .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbBookCount1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbBookCount2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbBookCount3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbBookCount4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbBookCount5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbBookCount6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbBookCount7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbBookCount8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbBookCount9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbBookCount10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbBookCount11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbBookCount12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbTotalCount)
                            .addComponent(jLabel16))))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnOuter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnOuter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void setBackground()
  {
          java.net.URL url = this.getClass().getResource("images/SMD_Library_Background.jpg");
          javax.swing.ImageIcon imageBack = new javax.swing.ImageIcon(url);
          javax.swing.JLabel jlbBackground = new javax.swing.JLabel(imageBack);
          jlbBackground.setBounds(0, 0,imageBack.getIconWidth(),imageBack.getIconHeight());
          getLayeredPane().add(jlbBackground, new Integer(Integer.MIN_VALUE));
          jpnOuter.setOpaque(false);
          setContentPane(jpnOuter);

  }
    private void jtfTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTitleActionPerformed

    private void jpnOuterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnOuterMouseClicked
        // TODO add your handling code here:
        String []printOption = {"Print","Do not print"};
        int receiptOption = JOptionPane.showOptionDialog(null,"Do you want to print out the report?","Report printing",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,printOption,printOption[1]);
        if(receiptOption == JOptionPane.YES_OPTION)
        {
            new LogFile().printReport(reportContent());
        }
        new UpdateBookPage(adm).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jpnOuterMouseClicked

    private String reportContent()
    {
        String rpt = "\n              Year "+year+" Sales Report\n\n"+
                    "MONTH        TOTAL RENTED BOOK        TOTAL REVENUE(RM)\n"+
                    "January               "+subCount[0]+"                     "+String.format("%.2f",subTotal[0])+"\n"+
                    "February              "+subCount[1]+"                     "+String.format("%.2f",subTotal[1])+"\n"+
                    "March                 "+subCount[2]+"                     "+String.format("%.2f",subTotal[2])+"\n"+
                    "April                 "+subCount[3]+"                     "+String.format("%.2f",subTotal[3])+"\n"+
                    "May                   "+subCount[4]+"                     "+String.format("%.2f",subTotal[4])+"\n"+
                    "June                  "+subCount[5]+"                     "+String.format("%.2f",subTotal[5])+"\n"+
                    "July                  "+subCount[6]+"                     "+String.format("%.2f",subTotal[6])+"\n"+
                    "August                "+subCount[7]+"                     "+String.format("%.2f",subTotal[7])+"\n"+
                    "September             "+subCount[8]+"                     "+String.format("%.2f",subTotal[8])+"\n"+
                    "October               "+subCount[9]+"                     "+String.format("%.2f",subTotal[9])+"\n"+
                    "November              "+subCount[10]+"                     "+String.format("%.2f",subTotal[10])+"\n"+
                    "December              "+subCount[11]+"                     "+String.format("%.2f",subTotal[11])+"\n"+
                    "Total                 "+count+"                     "+String.format("%.2f",total)+"\n";

        return rpt;
    }

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlbBookCount1;
    private javax.swing.JLabel jlbBookCount10;
    private javax.swing.JLabel jlbBookCount11;
    private javax.swing.JLabel jlbBookCount12;
    private javax.swing.JLabel jlbBookCount2;
    private javax.swing.JLabel jlbBookCount3;
    private javax.swing.JLabel jlbBookCount4;
    private javax.swing.JLabel jlbBookCount5;
    private javax.swing.JLabel jlbBookCount6;
    private javax.swing.JLabel jlbBookCount7;
    private javax.swing.JLabel jlbBookCount8;
    private javax.swing.JLabel jlbBookCount9;
    private javax.swing.JLabel jlbRevenue1;
    private javax.swing.JLabel jlbRevenue10;
    private javax.swing.JLabel jlbRevenue11;
    private javax.swing.JLabel jlbRevenue12;
    private javax.swing.JLabel jlbRevenue2;
    private javax.swing.JLabel jlbRevenue3;
    private javax.swing.JLabel jlbRevenue4;
    private javax.swing.JLabel jlbRevenue5;
    private javax.swing.JLabel jlbRevenue6;
    private javax.swing.JLabel jlbRevenue7;
    private javax.swing.JLabel jlbRevenue8;
    private javax.swing.JLabel jlbRevenue9;
    private javax.swing.JLabel jlbTotalCount;
    private javax.swing.JLabel jlbTotalRent;
    private javax.swing.JPanel jpnOuter;
    private javax.swing.JTextField jtfTitle;
    // End of variables declaration//GEN-END:variables

}
