/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Staffpage.java
 *
 * Created on Nov 16, 2009, 9:59:31 PM
 */

/**
 *
 * @author 17thkent
 */
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import javax.swing.ImageIcon;

public class StaffPage extends javax.swing.JFrame {

    private DefaultListModel receiptModel = new DefaultListModel();

    private ArrayList<String> receiptNo = new ArrayList<String>();

    private Database db = new Database();
    private Staff stf;
    private LogFile file;
    private int currentYear;
    private ImageIcon img;
    /** Creates new form Staffpage */
    public StaffPage(Staff stf) {
        this.stf = stf;
        file = new LogFile();
        img = new ImageIcon(this.getClass().getResource("images/SMD_Library_Background.jpg"));
        UIManager.put("TabbedPane.contentOpaque", Boolean.FALSE);
        initComponents();
        jtab.setOpaque(false);
        setBackground();
        jlbWelcome.setText("Hi, "+this.stf.getLastName());
        jlbID.setText("ID: "+this.stf.getID());
        
            jtfMemberID.setEnabled(false);
            jtfBookID.setEnabled(false);
            jbtSearch.setEnabled(false);
            jlblBookID.setEnabled(false);
            jlblMemberID.setEnabled(false);
            jListReceipt.setEnabled(false);
            setLocationRelativeTo(null);
        
        jpnReload.setOpaque(false);
        jpnReturn.setOpaque(false);
        jpnReload.setOpaque(false);
        jpnStaffInfo.setOpaque(false);

        jtfInfoFirstName.setText(stf.getFirstName());
        jtfInfoLastName.setText(stf.getLastName());
        jtfInfoID.setText(stf.getID());
        jtfInfoIC.setText(stf.getIC());
        jtfInfoPhoneNo.setText(stf.getPhone());
        jtfInfoGender.setText(stf.getGender());
        jtfInfoPosition.setText(stf.getPosition());
        jtfInfoSalary.setText(String.format("RM %.2f", stf.getSalary()));
        jtfInfoAddress.setText(stf.getAddress());
        jtfInfoPostcode.setText(stf.getPostcode());
        jtfInfoTown.setText(stf.getTown());
        jtfInfoState.setText(stf.getState());
        jtfInfoCountry.setText(stf.getCountry());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupReceipt = new javax.swing.ButtonGroup();
        jpnOuter = new javax.swing.JPanel()
        {
            protected void paintComponent(Graphics g){
                //  Scale image to size of component
                Dimension d = getSize();
                g.drawImage(img.getImage(), 0, 0, d.width, d.height, null);
                super.paintComponent(g);
            }
        }
        ;
        jtab = new javax.swing.JTabbedPane();
        jpnReturn = new javax.swing.JPanel();
        jlblReceipt = new javax.swing.JLabel();
        jtfReceipt = new javax.swing.JTextField();
        jlblMemberID = new javax.swing.JLabel();
        jlblBookID = new javax.swing.JLabel();
        jtfMemberID = new javax.swing.JTextField();
        jtfBookID = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jlblReturn = new javax.swing.JLabel();
        jtfDays = new javax.swing.JTextField();
        jlblDays = new javax.swing.JLabel();
        jlblFineRate = new javax.swing.JLabel();
        jlblRates = new javax.swing.JLabel();
        jlblTotalFine = new javax.swing.JLabel();
        jtfTotalFine = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtfBalanceAfterReturn = new javax.swing.JTextField();
        jbtReturnBook = new javax.swing.JButton();
        jrbUnknown = new javax.swing.JRadioButton();
        jrbKnown = new javax.swing.JRadioButton();
        jbtSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListReceipt = new javax.swing.JList();
        jpnReload = new javax.swing.JPanel()
        /*{
            protected void paintComponent(Graphics g){
                //  Scale image to size of component
                g.setColor( getBackground() );
                g.fillRect(0, 0, getWidth(), getHeight());
                super.paintComponent(g);
            }
        }*/
        ;
        jlblMember = new javax.swing.JLabel();
        jlblReload = new javax.swing.JLabel();
        jbtConfirm = new javax.swing.JButton();
        jtfMember = new javax.swing.JTextField();
        jtfReload = new javax.swing.JTextField();
        jtfTitle = new javax.swing.JTextField();
        jpnStaffInfo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtfInfoPhoneNo = new javax.swing.JTextField();
        jtfInfoID = new javax.swing.JTextField();
        jtfInfoFirstName = new javax.swing.JTextField();
        jtfInfoLastName = new javax.swing.JTextField();
        jtfInfoIC = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtfInfoGender = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtfInfoPosition = new javax.swing.JTextField();
        jtfInfoPostcode = new javax.swing.JTextField();
        jtfInfoSalary = new javax.swing.JTextField();
        jtfInfoState = new javax.swing.JTextField();
        jtfInfoCountry = new javax.swing.JTextField();
        jtfInfoTown = new javax.swing.JTextField();
        jtfInfoAddress = new javax.swing.JTextField();
        jlbEditProfile = new javax.swing.JLabel();
        jlbWelcome = new javax.swing.JLabel();
        jlbID = new javax.swing.JLabel();
        jlbLogout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Staff");
        setIconImage(new ImageIcon(getClass().getResource("images/HomeIcon.png")).getImage());
        setResizable(false);

        jlblReceipt.setFont(new java.awt.Font("Tahoma", 0, 12));
        jlblReceipt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblReceipt.setText("Receipt Number");
        jlblReceipt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtfReceipt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 153), 1, true));

        jlblMemberID.setFont(new java.awt.Font("Tahoma", 0, 12));
        jlblMemberID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblMemberID.setText("Member ID");
        jlblMemberID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlblBookID.setFont(new java.awt.Font("Tahoma", 0, 12));
        jlblBookID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblBookID.setText("ISBN");
        jlblBookID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtfMemberID.setToolTipText("Must be fill in");

        jtfBookID.setToolTipText("Optional");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlblReturn.setText("Late Return for ");

        jtfDays.setFont(new java.awt.Font("Arial", 1, 11));
        jtfDays.setForeground(new java.awt.Color(255, 0, 0));
        jtfDays.setCaretColor(new java.awt.Color(255, 0, 0));
        jtfDays.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        jtfDays.setEnabled(false);

        jlblDays.setText("days.");

        jlblFineRate.setText("Fine Rate");

        jlblRates.setText("x RM 0.50");

        jlblTotalFine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTotalFine.setText("Total Fine");
        jlblTotalFine.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        jtfTotalFine.setFont(new java.awt.Font("Arial", 1, 11));
        jtfTotalFine.setForeground(new java.awt.Color(255, 0, 0));
        jtfTotalFine.setCaretColor(new java.awt.Color(255, 0, 0));
        jtfTotalFine.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        jtfTotalFine.setEnabled(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Balance");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        jtfBalanceAfterReturn.setFont(new java.awt.Font("Arial", 1, 11));
        jtfBalanceAfterReturn.setForeground(new java.awt.Color(255, 0, 0));
        jtfBalanceAfterReturn.setCaretColor(new java.awt.Color(255, 0, 0));
        jtfBalanceAfterReturn.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        jtfBalanceAfterReturn.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlblFineRate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblReturn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblRates, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfDays, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblDays))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblTotalFine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfBalanceAfterReturn, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(jtfTotalFine, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))))
                .addGap(29, 29, 29))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblDays))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblFineRate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblRates, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTotalFine, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTotalFine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfBalanceAfterReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jbtReturnBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return.png"))); // NOI18N
        jbtReturnBook.setMnemonic('R');
        jbtReturnBook.setText("Return Book");
        jbtReturnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtReturnBookActionPerformed(evt);
            }
        });

        buttonGroupReceipt.add(jrbUnknown);
        jrbUnknown.setText("ReceiptNo is unknown");
        jrbUnknown.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jrbUnknownStateChanged(evt);
            }
        });

        buttonGroupReceipt.add(jrbKnown);
        jrbKnown.setSelected(true);
        jrbKnown.setText("ReceiptNo is known");

        jbtSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/229.png"))); // NOI18N
        jbtSearch.setMnemonic('S');
        jbtSearch.setText("search");
        jbtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSearchActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListReceipt);

        javax.swing.GroupLayout jpnReturnLayout = new javax.swing.GroupLayout(jpnReturn);
        jpnReturn.setLayout(jpnReturnLayout);
        jpnReturnLayout.setHorizontalGroup(
            jpnReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnReturnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbUnknown)
                    .addGroup(jpnReturnLayout.createSequentialGroup()
                        .addGroup(jpnReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnReturnLayout.createSequentialGroup()
                                .addComponent(jlblMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfMemberID, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                            .addGroup(jpnReturnLayout.createSequentialGroup()
                                .addComponent(jlblBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfBookID, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpnReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnReturnLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnReturnLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jlblReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnReturnLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jrbKnown))))
                    .addGroup(jpnReturnLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnReturnLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jbtSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                .addComponent(jbtReturnBook)
                .addGap(99, 99, 99))
        );
        jpnReturnLayout.setVerticalGroup(
            jpnReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnReturnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbUnknown)
                    .addComponent(jrbKnown))
                .addGroup(jpnReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnReturnLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnReturnLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jpnReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jpnReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtReturnBook))
                .addGap(19, 19, 19))
        );

        jtab.addTab("Return", jpnReturn);

        jlblMember.setFont(new java.awt.Font("Vani", 1, 10));
        jlblMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblMember.setText("Member ID");
        jlblMember.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlblReload.setFont(new java.awt.Font("Vani", 1, 10));
        jlblReload.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblReload.setText("Amount to be Reload");
        jlblReload.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbtConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/260.png"))); // NOI18N
        jbtConfirm.setMnemonic('C');
        jbtConfirm.setText("Confirm");
        jbtConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtConfirmActionPerformed(evt);
            }
        });

        jtfTitle.setBackground(new java.awt.Color(204, 204, 204));
        jtfTitle.setFont(new java.awt.Font("Arial", 1, 18));
        jtfTitle.setText("Member Reload Credit System");
        jtfTitle.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfTitle.setEnabled(false);

        javax.swing.GroupLayout jpnReloadLayout = new javax.swing.GroupLayout(jpnReload);
        jpnReload.setLayout(jpnReloadLayout);
        jpnReloadLayout.setHorizontalGroup(
            jpnReloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnReloadLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(jpnReloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblReload, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jlblMember, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(jpnReloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfMember, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfReload, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117))
            .addGroup(jpnReloadLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jtfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnReloadLayout.createSequentialGroup()
                .addContainerGap(551, Short.MAX_VALUE)
                .addComponent(jbtConfirm)
                .addGap(31, 31, 31))
        );
        jpnReloadLayout.setVerticalGroup(
            jpnReloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnReloadLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jtfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jpnReloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblMember, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfMember, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jpnReloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfReload)
                    .addComponent(jlblReload, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addComponent(jbtConfirm)
                .addGap(38, 38, 38))
        );

        jtab.addTab("Reload", jpnReload);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Staff ID");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtfInfoPhoneNo.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        jtfInfoPhoneNo.setEnabled(false);

        jtfInfoID.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        jtfInfoID.setEnabled(false);

        jtfInfoFirstName.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        jtfInfoFirstName.setEnabled(false);

        jtfInfoLastName.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        jtfInfoLastName.setEnabled(false);

        jtfInfoIC.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        jtfInfoIC.setEnabled(false);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Last Name");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Phone No.");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Gender");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("IC");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtfInfoGender.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        jtfInfoGender.setEnabled(false);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("First Name");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Country");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Address");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Town");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("State");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Postcode");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Salary");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Position");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtfInfoPosition.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        jtfInfoPosition.setEnabled(false);

        jtfInfoPostcode.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        jtfInfoPostcode.setEnabled(false);

        jtfInfoSalary.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        jtfInfoSalary.setEnabled(false);

        jtfInfoState.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        jtfInfoState.setEnabled(false);

        jtfInfoCountry.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        jtfInfoCountry.setEnabled(false);

        jtfInfoTown.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        jtfInfoTown.setEnabled(false);

        jtfInfoAddress.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        jtfInfoAddress.setEnabled(false);

        jlbEditProfile.setFont(new java.awt.Font("Arial", 1, 14));
        jlbEditProfile.setForeground(new java.awt.Color(51, 153, 0));
        jlbEditProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil-128x128.png"))); // NOI18N
        jlbEditProfile.setText("Edit Profile");
        jlbEditProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlbEditProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbEditProfileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbEditProfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbEditProfileMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpnStaffInfoLayout = new javax.swing.GroupLayout(jpnStaffInfo);
        jpnStaffInfo.setLayout(jpnStaffInfoLayout);
        jpnStaffInfoLayout.setHorizontalGroup(
            jpnStaffInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnStaffInfoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jpnStaffInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnStaffInfoLayout.createSequentialGroup()
                        .addGroup(jpnStaffInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpnStaffInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpnStaffInfoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfInfoID, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnStaffInfoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfInfoLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnStaffInfoLayout.createSequentialGroup()
                        .addGroup(jpnStaffInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                        .addGroup(jpnStaffInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnStaffInfoLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jpnStaffInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtfInfoPhoneNo, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addGroup(jpnStaffInfoLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfInfoCountry, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                                    .addComponent(jtfInfoTown, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addComponent(jtfInfoAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnStaffInfoLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jtfInfoGender, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGap(8, 8, 8)))
                .addGap(7, 7, 7)
                .addGroup(jpnStaffInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnStaffInfoLayout.createSequentialGroup()
                        .addGroup(jpnStaffInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(jpnStaffInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtfInfoState)
                            .addComponent(jtfInfoFirstName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfInfoPosition, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(jtfInfoSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(jtfInfoPostcode, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(jtfInfoIC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jlbEditProfile))
                .addGap(22, 22, 22))
        );
        jpnStaffInfoLayout.setVerticalGroup(
            jpnStaffInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnStaffInfoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jpnStaffInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfInfoID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfInfoIC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jpnStaffInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfInfoLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfInfoFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnStaffInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfInfoGender, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfInfoPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnStaffInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfInfoPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfInfoSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnStaffInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfInfoAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfInfoPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnStaffInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfInfoTown, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfInfoState, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpnStaffInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnStaffInfoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpnStaffInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfInfoCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnStaffInfoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbEditProfile)
                        .addGap(21, 21, 21))))
        );

        jtab.addTab("Staff Info", jpnStaffInfo);

        jlbWelcome.setFont(new java.awt.Font("Arial", 1, 14));
        jlbWelcome.setText("Hi");

        jlbID.setFont(new java.awt.Font("Arial", 1, 14));
        jlbID.setText("ID:");

        jlbLogout.setFont(new java.awt.Font("Arial", 1, 14));
        jlbLogout.setForeground(new java.awt.Color(51, 153, 0));
        jlbLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Log-Out.png"))); // NOI18N
        jlbLogout.setText("Log out");
        jlbLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlbLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbLogoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpnOuterLayout = new javax.swing.GroupLayout(jpnOuter);
        jpnOuter.setLayout(jpnOuterLayout);
        jpnOuterLayout.setHorizontalGroup(
            jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnOuterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnOuterLayout.createSequentialGroup()
                        .addComponent(jlbWelcome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 599, Short.MAX_VALUE)
                        .addComponent(jlbLogout)
                        .addGap(14, 14, 14))
                    .addComponent(jlbID)
                    .addComponent(jtab, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jpnOuterLayout.setVerticalGroup(
            jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnOuterLayout.createSequentialGroup()
                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpnOuterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbWelcome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbID))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnOuterLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbLogout)
                        .addGap(19, 19, 19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtab, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnOuter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnOuter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtConfirmActionPerformed
        // TODO add your handling code here:
        double balance = 0.0;
        if(jtfMember.getText().equals("") || jtfReload.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Incomplete information!","Invalid",JOptionPane.ERROR_MESSAGE);
        else
        {
            try{
                int x = JOptionPane.showConfirmDialog(null,"Are you sure you want to reload RM"+jtfReload.getText()+"?","Confirm?",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                if(x == JOptionPane.YES_OPTION)
                {
                    balance = db.reloadBalance(jtfMember.getText(),Double.parseDouble(jtfReload.getText()));
                    if(balance == 0.0)
                        JOptionPane.showMessageDialog(null,"Invalid User ID! Please re-check...","Invalid",JOptionPane.ERROR_MESSAGE);
                    else{
                        JOptionPane.showMessageDialog(null,"Reload Successful! Your current balance is RM"+String.format("%.2f", balance));
                        jtab.setSelectedIndex(0);
                        jtfMember.setText("");
                        jtfReload.setText("");
                    }
                }
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Invalid! Balance should only digits.","Invalid",JOptionPane.ERROR_MESSAGE);
                file.exceptionRecord(e.getStackTrace());
            }
            catch(NullPointerException e){
                JOptionPane.showMessageDialog(null,"NullPointerException: "+e.getMessage(),"Invalid",JOptionPane.ERROR_MESSAGE);
                file.exceptionRecord(e.getStackTrace());
            }
        }
    }//GEN-LAST:event_jbtConfirmActionPerformed

    private void jbtReturnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtReturnBookActionPerformed
        // TODO add your handling code here:
        int dayBorrow = 0;
        double balance = 0.0;
        int index = jListReceipt.getSelectedIndex();
        String selectedReceipt = "";
        if(jrbUnknown.isSelected())
        {
            if(jListReceipt.isSelectionEmpty())
            {
                JOptionPane.showMessageDialog(null,"Please choose a selection!","Incomplete Information",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                selectedReceipt = receiptNo.get(index).substring(13, 21);
                int x = JOptionPane.showConfirmDialog(null,"Are you sure you want to return this book?","Return book",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);

                if(x == JOptionPane.YES_OPTION)
                {
                    dayBorrow = db.returnBook(selectedReceipt);
                    if(dayBorrow!=-1)
                    {
                        balance = db.retrieveBalance(selectedReceipt);
                        receiptModel.removeElementAt(index);
                        receiptNo.remove(index);
                    }
                }
                else
                {
                    jtfDays.setText(dayBorrow+"");
                    jtfTotalFine.setText((dayBorrow*0.5)+"");
                    jtfBalanceAfterReturn.setText(balance+"");
                }
            }
        }
        else
        {
            if(jtfReceipt.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null,"Please enter receipt no.!","Incomplete Information",JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                selectedReceipt = jtfReceipt.getText();
                int x = JOptionPane.showConfirmDialog(null,"Are you sure you want to return this book?","Return book",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);

                if(x == JOptionPane.YES_OPTION)
                {
                    dayBorrow = db.returnBook(selectedReceipt);
                    if(dayBorrow!=-1)
                    {
                        balance = db.retrieveBalance(selectedReceipt);
                    }
                }
                else
                {
                    jtfDays.setText(dayBorrow+"");
                    jtfTotalFine.setText((dayBorrow*0.5)+"");
                    jtfBalanceAfterReturn.setText(balance+"");
                }
            }
        }
        if(dayBorrow>=0)
        {
            jtfDays.setText(dayBorrow+"");
            jtfTotalFine.setText((dayBorrow*0.5)+"");
            jtfBalanceAfterReturn.setText(balance+"");
        }
    }//GEN-LAST:event_jbtReturnBookActionPerformed

    private void jlbLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbLogoutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new LoginPage().setVisible(true);
}//GEN-LAST:event_jlbLogoutMouseClicked

    private void jlbLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbLogoutMouseEntered
        // TODO add your handling code here:
        jlbLogout.setFont(new Font("Arial",Font.BOLD,14));
        jlbLogout.setForeground(Color.red);
}//GEN-LAST:event_jlbLogoutMouseEntered

    private void jlbLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbLogoutMouseExited
        // TODO add your handling code here:
        jlbLogout.setFont(new Font("Arial",Font.BOLD,14));
        jlbLogout.setForeground(new Color(51, 153, 0));
}//GEN-LAST:event_jlbLogoutMouseExited

    private void jrbUnknownStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jrbUnknownStateChanged
        // TODO add your handling code here:
        if(jrbUnknown.isSelected())
        {
            jlblReceipt.setEnabled(false);
            jtfReceipt.setEnabled(false);
            jtfMemberID.setEnabled(true);
            jtfMemberID.setBackground(Color.YELLOW);
            jtfBookID.setEnabled(true);
            jbtSearch.setEnabled(true);
            jlblBookID.setEnabled(true);
            jlblMemberID.setEnabled(true);
            jtfReceipt.setText("");
            jListReceipt.setEnabled(true);
        }
        else
        {
            jlblReceipt.setEnabled(true);
            jtfReceipt.setEnabled(true);
            jtfMemberID.setEnabled(false);
            jtfMemberID.setBackground(Color.WHITE);
            jtfBookID.setEnabled(false);
            jbtSearch.setEnabled(false);
            jlblBookID.setEnabled(false);
            jlblMemberID.setEnabled(false);
            jListReceipt.setEnabled(false);
            jListReceipt.clearSelection();
        }
    }//GEN-LAST:event_jrbUnknownStateChanged

    private void jbtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSearchActionPerformed
        // TODO add your handling code here:
        receiptNo = null;
        receiptModel.removeAllElements();
        jListReceipt.setModel(receiptModel);
        if(jtfMemberID.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Please enter Member ID!","Incomplete Information",JOptionPane.PLAIN_MESSAGE);
        else
        {
            receiptNo = db.searchReceiptNo(jtfMemberID.getText(),jtfBookID.getText());

            if(receiptNo==null)
                JOptionPane.showMessageDialog(null,"No record found!","No record",JOptionPane.PLAIN_MESSAGE);
            else
            {
                for(int i=0;i<receiptNo.size();i++)
                {
                    receiptModel.addElement(receiptNo.get(i));
                }
                jListReceipt.setModel(receiptModel);
            }
        }
    }//GEN-LAST:event_jbtSearchActionPerformed

    private void jlbEditProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbEditProfileMouseClicked
        // TODO add your handling code here:
        new StaffEditProfile(stf).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlbEditProfileMouseClicked

    private void jlbEditProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbEditProfileMouseEntered
        // TODO add your handling code here:
        jlbEditProfile.setFont(new Font("Arial",Font.BOLD,14));
        jlbEditProfile.setForeground(Color.red);
    }//GEN-LAST:event_jlbEditProfileMouseEntered

    private void jlbEditProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbEditProfileMouseExited
        // TODO add your handling code here:
        jlbEditProfile.setFont(new Font("Arial",Font.BOLD,14));
        jlbEditProfile.setForeground(new Color(51, 153, 0));
    }//GEN-LAST:event_jlbEditProfileMouseExited

  private void setBackground()
  {
          java.net.URL url = this.getClass().getResource("images/SMD_Library_Background.jpg");
          ImageIcon imageBack = new ImageIcon(url);
          JLabel jlbBackground = new JLabel(imageBack);
          jlbBackground.setBounds(0, 0,imageBack.getIconWidth(),imageBack.getIconHeight());
          getLayeredPane().add(jlbBackground, new Integer(Integer.MIN_VALUE));
          jpnOuter.setOpaque(false);
          setContentPane(jpnOuter);

  }

   
    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupReceipt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jListReceipt;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtConfirm;
    private javax.swing.JButton jbtReturnBook;
    private javax.swing.JButton jbtSearch;
    private javax.swing.JLabel jlbEditProfile;
    private javax.swing.JLabel jlbID;
    private javax.swing.JLabel jlbLogout;
    private javax.swing.JLabel jlbWelcome;
    private javax.swing.JLabel jlblBookID;
    private javax.swing.JLabel jlblDays;
    private javax.swing.JLabel jlblFineRate;
    private javax.swing.JLabel jlblMember;
    private javax.swing.JLabel jlblMemberID;
    private javax.swing.JLabel jlblRates;
    private javax.swing.JLabel jlblReceipt;
    private javax.swing.JLabel jlblReload;
    private javax.swing.JLabel jlblReturn;
    private javax.swing.JLabel jlblTotalFine;
    private javax.swing.JPanel jpnOuter;
    private javax.swing.JPanel jpnReload;
    private javax.swing.JPanel jpnReturn;
    private javax.swing.JPanel jpnStaffInfo;
    private javax.swing.JRadioButton jrbKnown;
    private javax.swing.JRadioButton jrbUnknown;
    private javax.swing.JTabbedPane jtab;
    private javax.swing.JTextField jtfBalanceAfterReturn;
    private javax.swing.JTextField jtfBookID;
    private javax.swing.JTextField jtfDays;
    private javax.swing.JTextField jtfInfoAddress;
    private javax.swing.JTextField jtfInfoCountry;
    private javax.swing.JTextField jtfInfoFirstName;
    private javax.swing.JTextField jtfInfoGender;
    private javax.swing.JTextField jtfInfoIC;
    private javax.swing.JTextField jtfInfoID;
    private javax.swing.JTextField jtfInfoLastName;
    private javax.swing.JTextField jtfInfoPhoneNo;
    private javax.swing.JTextField jtfInfoPosition;
    private javax.swing.JTextField jtfInfoPostcode;
    private javax.swing.JTextField jtfInfoSalary;
    private javax.swing.JTextField jtfInfoState;
    private javax.swing.JTextField jtfInfoTown;
    private javax.swing.JTextField jtfMember;
    private javax.swing.JTextField jtfMemberID;
    private javax.swing.JTextField jtfReceipt;
    private javax.swing.JTextField jtfReload;
    private javax.swing.JTextField jtfTitle;
    private javax.swing.JTextField jtfTotalFine;
    // End of variables declaration//GEN-END:variables

}
