/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UpdateBookPage.java
 *
 * Created on Nov 26, 2009, 3:19:36 PM
 */
/**
 *
 * @author Js Lim
 */
import java.util.ArrayList;
import javax.swing.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

public class UpdateBookPage extends javax.swing.JFrame {

    //For Delete
    private ArrayList<String> arrAddedBook = new ArrayList<String>();
    private DefaultListModel searchBookModel = new DefaultListModel();
    private ArrayList<Book> arrBook;
    //For Update
    private ArrayList<String> arrUpdateList = new ArrayList<String>();
    private DefaultListModel updateBookModel = new DefaultListModel();
    private ArrayList<Book> arrUpdateBook;
    private Database db = new Database();
    private Staff admin = new Staff();
    private ImageIcon img;
    private DefaultComboBoxModel yearModel;

    /** Creates new form UpdateBookPage */
    public UpdateBookPage(Staff admin) {
        img = new ImageIcon(this.getClass().getResource("images/SMD_Library_Background.jpg"));
        yearModel = new DefaultComboBoxModel();
        for (int i = (Integer.parseInt(getYear())); i >= 2008; i--) {
            yearModel.addElement(i);
        }
        UIManager.put("TabbedPane.contentOpaque", Boolean.FALSE);
        initComponents();
        jcbYear.setModel(yearModel);
        setBackground();
        this.admin = admin;
        jtaDescription.setLineWrap(true);
        jlbWelcome.setText("Hi, " + admin.getLastName());
        setLocationRelativeTo(null);
        jtbAdmin.setOpaque(false);
        jpnInsert.setOpaque(false);
        jpnUpdate.setOpaque(false);
        jpnDelete.setOpaque(false);
        jpnStaff.setOpaque(false);
        jlbPosition.setEnabled(false);
        jlbSalary.setEnabled(false);
        jcbPosition.setEnabled(false);
        jtfSalary.setEnabled(false);
        jlbPassword.setEnabled(true);
        jbtRetrieve.setEnabled(true);
        jbtUpdateStaffStatus.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupStaff = new javax.swing.ButtonGroup();
        buttonGroupReport = new javax.swing.ButtonGroup();
        jpnOuter = new javax.swing.JPanel()
        {
            protected void paintComponent(Graphics g){
                //  Scale image to size of component
                Dimension d = getSize();
                g.drawImage(img.getImage(), 0, 0, d.width, d.height, null);
                super.paintComponent(g);
            }
        }
        ;
        jtbAdmin = new javax.swing.JTabbedPane();
        jpnInsert = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfISBN = new javax.swing.JTextField();
        jtfTitle = new javax.swing.JTextField();
        jtfPublisher = new javax.swing.JTextField();
        jtfAuthor = new javax.swing.JTextField();
        jtfRentPrice = new javax.swing.JTextField();
        jtfQuantity = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDescription = new javax.swing.JTextArea();
        jcbType = new javax.swing.JComboBox();
        jbtInsert = new javax.swing.JButton();
        jbtClearInsert = new javax.swing.JButton();
        jpnDelete = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jltSearchResult = new javax.swing.JList();
        jcbSearch = new javax.swing.JComboBox();
        jlbSearch = new javax.swing.JLabel();
        jtfSearch = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jbtSearch = new javax.swing.JButton();
        jbtDelete = new javax.swing.JButton();
        jbtClearDelete = new javax.swing.JButton();
        jpnUpdate = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jltSearchedBook = new javax.swing.JList();
        jcbSearchUpdate = new javax.swing.JComboBox();
        jlbSearch1 = new javax.swing.JLabel();
        jtfSearchUpdate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jbtSearchUpdate = new javax.swing.JButton();
        jbtUpdate = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtfRentPriceUpdate = new javax.swing.JTextField();
        jtfQuantityUpdate = new javax.swing.JTextField();
        jbtClearUpdate = new javax.swing.JButton();
        jpnStaff = new javax.swing.JPanel();
        jlbStaffID = new javax.swing.JLabel();
        jcbPosition = new javax.swing.JComboBox();
        jlbPosition = new javax.swing.JLabel();
        jlbSalary = new javax.swing.JLabel();
        jtfSalary = new javax.swing.JTextField();
        jrbRetrievePassword = new javax.swing.JRadioButton();
        jrbEditStaff = new javax.swing.JRadioButton();
        jtfStaffID = new javax.swing.JTextField();
        jlbPassword = new javax.swing.JLabel();
        jtfPassword = new javax.swing.JTextField();
        jbtRetrieve = new javax.swing.JButton();
        jbtUpdateStaffStatus = new javax.swing.JButton();
        jlbNewStaffRegister = new javax.swing.JLabel();
        jlbWelcome = new javax.swing.JLabel();
        jlbLogout = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jcbYear = new javax.swing.JComboBox();
        jbtViewReport = new javax.swing.JButton();
        jrbSalesReport = new javax.swing.JRadioButton();
        jrbBookReport = new javax.swing.JRadioButton();
        jrbTotalRentReport = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administration");
        setIconImage(new ImageIcon(getClass().getResource("images/HomeIcon.png")).getImage());
        setResizable(false);

        jLabel1.setText("ISBN");

        jLabel2.setText("Title");

        jLabel3.setText("Publisher");

        jLabel4.setText("Type");

        jLabel5.setText("Author");

        jLabel6.setText("Rent Price");

        jLabel7.setText("Quantity");

        jLabel8.setText("Description");

        jtaDescription.setColumns(20);
        jtaDescription.setRows(5);
        jScrollPane1.setViewportView(jtaDescription);

        jcbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Comic", "Reference", "Fiction", "Non-Fiction", "Documentary" }));

        jbtInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vista (198).png"))); // NOI18N
        jbtInsert.setMnemonic('I');
        jbtInsert.setText("Insert");
        jbtInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtInsertActionPerformed(evt);
            }
        });

        jbtClearInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Symbols-Delete-256x256.png"))); // NOI18N
        jbtClearInsert.setMnemonic('C');
        jbtClearInsert.setText("Clear");
        jbtClearInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtClearInsertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnInsertLayout = new javax.swing.GroupLayout(jpnInsert);
        jpnInsert.setLayout(jpnInsertLayout);
        jpnInsertLayout.setHorizontalGroup(
            jpnInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnInsertLayout.createSequentialGroup()
                .addGroup(jpnInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnInsertLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpnInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jpnInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                .addComponent(jtfPublisher, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                .addComponent(jtfAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                .addComponent(jcbType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfISBN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtfRentPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnInsertLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jbtInsert)))
                .addGroup(jpnInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnInsertLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jbtClearInsert))
                    .addGroup(jpnInsertLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jpnInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(30, 30, 30))
        );
        jpnInsertLayout.setVerticalGroup(
            jpnInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnInsertLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jpnInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addGroup(jpnInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnInsertLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jpnInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtfAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jcbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtfRentPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpnInsertLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(jpnInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtInsert)
                    .addComponent(jbtClearInsert))
                .addContainerGap())
        );

        jtbAdmin.addTab("Insert", jpnInsert);

        jltSearchResult.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jltSearchResult);

        jcbSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ISBN", "Title", "Publisher", "Author", "Type", "Description" }));
        jcbSearch.setSelectedIndex(1);

        jlbSearch.setText("Search for");

        jLabel9.setText("Searched Books");

        jbtSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/229.png"))); // NOI18N
        jbtSearch.setMnemonic('S');
        jbtSearch.setText("Search");
        jbtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSearchActionPerformed(evt);
            }
        });

        jbtDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/recyclebin.png"))); // NOI18N
        jbtDelete.setMnemonic('D');
        jbtDelete.setText("Delete");
        jbtDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDeleteActionPerformed(evt);
            }
        });

        jbtClearDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Symbols-Delete-256x256.png"))); // NOI18N
        jbtClearDelete.setMnemonic('l');
        jbtClearDelete.setText("Clear");
        jbtClearDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtClearDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnDeleteLayout = new javax.swing.GroupLayout(jpnDelete);
        jpnDelete.setLayout(jpnDeleteLayout);
        jpnDeleteLayout.setHorizontalGroup(
            jpnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDeleteLayout.createSequentialGroup()
                .addGroup(jpnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnDeleteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbSearch)
                        .addGap(18, 18, 18)
                        .addComponent(jcbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnDeleteLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jbtSearch)))
                .addGroup(jpnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnDeleteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnDeleteLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jpnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtClearDelete, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(60, 60, 60)
                        .addComponent(jbtDelete)))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(jpnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpnDeleteLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jpnDeleteLayout.setVerticalGroup(
            jpnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbSearch)
                    .addComponent(jcbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addGroup(jpnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSearch)
                    .addComponent(jbtDelete)
                    .addComponent(jbtClearDelete))
                .addGap(20, 20, 20))
            .addGroup(jpnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpnDeleteLayout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(112, Short.MAX_VALUE)))
        );

        jtbAdmin.addTab("Delete", jpnDelete);

        jltSearchedBook.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jltSearchedBook.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jltSearchedBookValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jltSearchedBook);

        jcbSearchUpdate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ISBN", "Title", "Publisher", "Author", "Type", "Description" }));
        jcbSearchUpdate.setSelectedIndex(1);

        jlbSearch1.setText("Search for");

        jLabel10.setText("Searched Books");

        jbtSearchUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/229.png"))); // NOI18N
        jbtSearchUpdate.setMnemonic('e');
        jbtSearchUpdate.setText("Search");
        jbtSearchUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSearchUpdateActionPerformed(evt);
            }
        });

        jbtUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DD_automatic_update_icon.png"))); // NOI18N
        jbtUpdate.setMnemonic('U');
        jbtUpdate.setText("Update");
        jbtUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUpdateActionPerformed(evt);
            }
        });

        jLabel11.setText("Rent Price");

        jLabel12.setText("Quantity");

        jbtClearUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Symbols-Delete-256x256.png"))); // NOI18N
        jbtClearUpdate.setMnemonic('r');
        jbtClearUpdate.setText("Clear");
        jbtClearUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtClearUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnUpdateLayout = new javax.swing.GroupLayout(jpnUpdate);
        jpnUpdate.setLayout(jpnUpdateLayout);
        jpnUpdateLayout.setHorizontalGroup(
            jpnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnUpdateLayout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addGroup(jpnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jtfRentPriceUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jbtUpdate)
                        .addComponent(jtfQuantityUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
            .addGroup(jpnUpdateLayout.createSequentialGroup()
                .addGroup(jpnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnUpdateLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jpnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnUpdateLayout.createSequentialGroup()
                                .addComponent(jlbSearch1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbSearchUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(jtfSearchUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnUpdateLayout.createSequentialGroup()
                                .addComponent(jbtSearchUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                .addComponent(jbtClearUpdate)
                                .addGap(54, 54, 54))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnUpdateLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel10)))
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(jpnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpnUpdateLayout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(195, Short.MAX_VALUE)))
        );
        jpnUpdateLayout.setVerticalGroup(
            jpnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbSearchUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbSearch1)
                    .addComponent(jtfSearchUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(13, 13, 13)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfRentPriceUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jtfQuantityUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(jpnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSearchUpdate)
                    .addComponent(jbtUpdate)
                    .addComponent(jbtClearUpdate))
                .addGap(20, 20, 20))
            .addGroup(jpnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpnUpdateLayout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(112, Short.MAX_VALUE)))
        );

        jtbAdmin.addTab("Update", jpnUpdate);

        jlbStaffID.setText("Staff ID");

        jcbPosition.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cashier", "Supervisor", "Manager" }));

        jlbPosition.setText("Position");

        jlbSalary.setText("Salary");

        buttonGroupStaff.add(jrbRetrievePassword);
        jrbRetrievePassword.setSelected(true);
        jrbRetrievePassword.setText("Retrieve Staff Password");
        jrbRetrievePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbRetrievePasswordActionPerformed(evt);
            }
        });

        buttonGroupStaff.add(jrbEditStaff);
        jrbEditStaff.setText("Edit Staff Status");
        jrbEditStaff.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jrbEditStaffStateChanged(evt);
            }
        });

        jlbPassword.setText("Password");

        jtfPassword.setBackground(new java.awt.Color(255, 255, 51));
        jtfPassword.setEditable(false);
        jtfPassword.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        jtfPassword.setEnabled(false);

        jbtRetrieve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icoDownload.png"))); // NOI18N
        jbtRetrieve.setMnemonic('R');
        jbtRetrieve.setText("Retrieve");
        jbtRetrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRetrieveActionPerformed(evt);
            }
        });

        jbtUpdateStaffStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DD_automatic_update_icon.png"))); // NOI18N
        jbtUpdateStaffStatus.setMnemonic('U');
        jbtUpdateStaffStatus.setText("Update");
        jbtUpdateStaffStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUpdateStaffStatusActionPerformed(evt);
            }
        });

        jlbNewStaffRegister.setFont(new java.awt.Font("Arial", 1, 14));
        jlbNewStaffRegister.setForeground(new java.awt.Color(51, 153, 0));
        jlbNewStaffRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/front_register.png"))); // NOI18N
        jlbNewStaffRegister.setText("New Staff Register");
        jlbNewStaffRegister.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlbNewStaffRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbNewStaffRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbNewStaffRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbNewStaffRegisterMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpnStaffLayout = new javax.swing.GroupLayout(jpnStaff);
        jpnStaff.setLayout(jpnStaffLayout);
        jpnStaffLayout.setHorizontalGroup(
            jpnStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnStaffLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jpnStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnStaffLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbPassword)
                        .addGap(18, 18, 18)
                        .addComponent(jtfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(jpnStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbPosition)
                            .addComponent(jlbSalary))
                        .addGap(34, 34, 34)
                        .addGroup(jpnStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfSalary)
                            .addComponent(jcbPosition, 0, 121, Short.MAX_VALUE))
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(jpnStaffLayout.createSequentialGroup()
                        .addComponent(jrbRetrievePassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addComponent(jrbEditStaff)
                        .addGap(96, 96, 96))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnStaffLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jbtRetrieve)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(jbtUpdateStaffStatus)
                .addGap(84, 84, 84))
            .addGroup(jpnStaffLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jlbStaffID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(jpnStaffLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jlbNewStaffRegister)
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jpnStaffLayout.setVerticalGroup(
            jpnStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnStaffLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jpnStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbStaffID)
                    .addComponent(jtfStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnStaffLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jpnStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbRetrievePassword)
                            .addComponent(jrbEditStaff))
                        .addGap(38, 38, 38)
                        .addGroup(jpnStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbPassword)))
                    .addGroup(jpnStaffLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jpnStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbPosition)
                            .addComponent(jcbPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbSalary)
                            .addComponent(jtfSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jpnStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnStaffLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jbtRetrieve))
                    .addGroup(jpnStaffLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jbtUpdateStaffStatus)
                        .addGap(39, 39, 39)
                        .addComponent(jlbNewStaffRegister)))
                .addGap(53, 53, 53))
        );

        jtbAdmin.addTab("Staff status", jpnStaff);

        jlbWelcome.setFont(new java.awt.Font("Arial", 1, 14));
        jlbWelcome.setText("Hi");

        jlbLogout.setFont(new java.awt.Font("Arial", 1, 14));
        jlbLogout.setForeground(new java.awt.Color(51, 153, 0));
        jlbLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Log-Out.png"))); // NOI18N
        jlbLogout.setText("Log out");
        jlbLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlbLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbLogoutMouseExited(evt);
            }
        });

        jLabel13.setText("Year");

        jcbYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2009" }));

        jbtViewReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ViewNews.png"))); // NOI18N
        jbtViewReport.setMnemonic('V');
        jbtViewReport.setText("View Report");
        jbtViewReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtViewReportMouseClicked(evt);
            }
        });

        buttonGroupReport.add(jrbSalesReport);
        jrbSalesReport.setSelected(true);
        jrbSalesReport.setText("Sales Report");
        jrbSalesReport.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jrbSalesReportStateChanged(evt);
            }
        });

        buttonGroupReport.add(jrbBookReport);
        jrbBookReport.setText("Book Report");

        buttonGroupReport.add(jrbTotalRentReport);
        jrbTotalRentReport.setText("Total Rent Report");

        javax.swing.GroupLayout jpnOuterLayout = new javax.swing.GroupLayout(jpnOuter);
        jpnOuter.setLayout(jpnOuterLayout);
        jpnOuterLayout.setHorizontalGroup(
            jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnOuterLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnOuterLayout.createSequentialGroup()
                        .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jpnOuterLayout.createSequentialGroup()
                                .addComponent(jlbWelcome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbLogout))
                            .addComponent(jtbAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(jpnOuterLayout.createSequentialGroup()
                        .addComponent(jrbSalesReport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jrbBookReport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbTotalRentReport)
                        .addGap(18, 18, 18)
                        .addComponent(jbtViewReport)
                        .addGap(38, 38, 38))))
        );
        jpnOuterLayout.setVerticalGroup(
            jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnOuterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbLogout)
                    .addComponent(jlbWelcome))
                .addGap(18, 18, 18)
                .addGroup(jpnOuterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbSalesReport)
                    .addComponent(jLabel13)
                    .addComponent(jcbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtViewReport)
                    .addComponent(jrbTotalRentReport)
                    .addComponent(jrbBookReport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtbAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnOuter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnOuter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtInsertActionPerformed
        // TODO add your handling code here:
        if (jtfISBN.getText().equals("") || jtfTitle.getText().equals("") || jtfPublisher.getText().equals("") || jtfAuthor.getText().equals("") || jtfRentPrice.getText().equals("") || jtfQuantity.getText().equals("") || jtaDescription.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Incomplete Information! Please fill in all the field.", "Incomplete", JOptionPane.ERROR_MESSAGE);
        } else {
            try{
                Book b = new Book();
                b.setISBN(jtfISBN.getText());
                b.setTitle(jtfTitle.getText());
                b.setPublisher(jtfPublisher.getText());
                b.setAuthor(jtfAuthor.getText());
                b.setRentPrice(Double.parseDouble(jtfRentPrice.getText()));
                b.setQuantity(Integer.parseInt(jtfQuantity.getText()));
                b.setType((String) jcbType.getSelectedItem());
                b.setDescription(jtaDescription.getText());
                db.addBook(b);
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Price & Quantity can only contain digits!","ERROR",JOptionPane.ERROR_MESSAGE);
            }

        }

    }//GEN-LAST:event_jbtInsertActionPerformed

    private void jbtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSearchActionPerformed
        // TODO add your handling code here:
        int index = jcbSearch.getSelectedIndex();
        Book book = new Book();
        String keyword = jtfSearch.getText();

        if (arrBook != null) {
            JOptionPane.showMessageDialog(null, "Please clear the result first!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (keyword.equals("")) {
            JOptionPane.showMessageDialog(null, "No record found!", "Not found", JOptionPane.WARNING_MESSAGE);
        } else {

            switch (index) {
                case 0: {
                    book.setISBN(keyword);
                    break;
                }
                case 1: {
                    book.setTitle(keyword);
                    break;
                }
                case 2: {
                    book.setPublisher(keyword);
                    break;
                }
                case 3: {
                    book.setAuthor(keyword);
                    break;
                }
                case 4: {
                    book.setType(keyword);
                    break;
                }
                case 5: {
                    book.setDescription(keyword);
                    break;
                }
                default:
                    break;
            }

            arrBook = db.adminBookSearch(book);
            if (arrBook == null) {
                JOptionPane.showMessageDialog(null, "No record found!", "Not found", JOptionPane.WARNING_MESSAGE);
            } else {
                for (int i = 0; i < arrBook.size(); i++) {
                    arrAddedBook.add("<" + arrBook.get(i).getTitle() + ">" + " by " + arrBook.get(i).getAuthor());
                    searchBookModel.addElement(arrAddedBook.get(i));
                }
                jltSearchResult.setModel(searchBookModel);
            }
        }
}//GEN-LAST:event_jbtSearchActionPerformed

    private void jbtSearchUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSearchUpdateActionPerformed
        // TODO add your handling code here:
        int index = jcbSearchUpdate.getSelectedIndex();
        Book bookUpdate = new Book();
        String keyword = jtfSearchUpdate.getText();

        if (arrUpdateBook != null) {
            JOptionPane.showMessageDialog(null, "Please clear the result first!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (keyword.equals("")) {
            JOptionPane.showMessageDialog(null, "No record found!", "Not found", JOptionPane.WARNING_MESSAGE);
        } else {

            switch (index) {
                case 0: {
                    bookUpdate.setISBN(keyword);
                    break;
                }
                case 1: {
                    bookUpdate.setTitle(keyword);
                    break;
                }
                case 2: {
                    bookUpdate.setPublisher(keyword);
                    break;
                }
                case 3: {
                    bookUpdate.setAuthor(keyword);
                    break;
                }
                case 4: {
                    bookUpdate.setType(keyword);
                    break;
                }
                case 5: {
                    bookUpdate.setDescription(keyword);
                    break;
                }
                default:
                    break;
            }

            arrUpdateBook = db.adminBookSearch(bookUpdate);
            if (arrUpdateBook == null) {
                JOptionPane.showMessageDialog(null, "No record found!", "Not found", JOptionPane.WARNING_MESSAGE);
            } else {
                for (int i = 0; i < arrUpdateBook.size(); i++) {
                    arrUpdateList.add("<" + arrUpdateBook.get(i).getTitle() + ">" + " by " + arrUpdateBook.get(i).getAuthor());
                    updateBookModel.addElement(arrUpdateList.get(i));
                }
                jltSearchedBook.setModel(updateBookModel);
            }
        }
    }//GEN-LAST:event_jbtSearchUpdateActionPerformed

    private void jbtUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUpdateActionPerformed
        // TODO add your handling code here:
        if (jltSearchedBook.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Nothing selected!", "Empty", JOptionPane.WARNING_MESSAGE);
        } else {
            int index = jltSearchedBook.getSelectedIndex();
            Book temp = arrUpdateBook.get(index);
            int x = JOptionPane.showConfirmDialog(null, "Are you sure want to update this book?", "Book update", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (x == JOptionPane.YES_OPTION) {
                if (!jtfRentPriceUpdate.getText().equals("")) {
                    temp.setRentPrice(Double.parseDouble(jtfRentPriceUpdate.getText()));
                }
                if (!jtfQuantityUpdate.getText().equals("")) {
                    temp.setQuantity(Integer.parseInt(jtfQuantityUpdate.getText()));
                }
                db.updateBook(temp);
                arrUpdateBook.get(index).setQuantity(temp.getQuantity());
                arrUpdateBook.get(index).setRentPrice(temp.getRentPrice());
            }
        }

    }//GEN-LAST:event_jbtUpdateActionPerformed

    private void jbtDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDeleteActionPerformed
        // TODO add your handling code here:
        if (jltSearchResult.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Nothing selected!", "Empty", JOptionPane.WARNING_MESSAGE);
        } else {
            int index = jltSearchResult.getSelectedIndex();
            String detail = "ISBN: " + arrBook.get(index).getISBN() +
                    "\nTitle: " + arrBook.get(index).getTitle() +
                    "\nPublisher: " + arrBook.get(index).getPublisher() +
                    "\nAuthor: " + arrBook.get(index).getAuthor() +
                    "\nType: " + arrBook.get(index).getTitle() +
                    "\nRent Price: " + arrBook.get(index).getRentPrice() +
                    "\nQuantity: " + arrBook.get(index).getQuantity() +
                    "\nDescription:\n " + arrBook.get(index).getDescription();
            int x = JOptionPane.showConfirmDialog(null, detail, "Are you sure want to delete this book?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (x == JOptionPane.YES_OPTION) {
                db.deleteBook(arrBook.get(index).getISBN());
                arrBook.remove(index);
                arrAddedBook.remove(index);
                searchBookModel.removeElementAt(index);
                jltSearchResult.setModel(searchBookModel);
            }
        }
    }//GEN-LAST:event_jbtDeleteActionPerformed

    private void jbtClearInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtClearInsertActionPerformed
        // TODO add your handling code here:
        jtfISBN.setText("");
        jtfTitle.setText("");
        jtfPublisher.setText("");
        jtfAuthor.setText("");
        jtfRentPrice.setText("");
        jtfQuantity.setText("");
        jcbType.setSelectedIndex(0);
        jtaDescription.setText("");
    }//GEN-LAST:event_jbtClearInsertActionPerformed

    private void jbtClearDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtClearDeleteActionPerformed
        // TODO add your handling code here:
        jcbSearch.setSelectedIndex(1);
        arrBook = null;
        arrAddedBook.clear();
        searchBookModel.removeAllElements();
        jltSearchResult.setModel(searchBookModel);
        jtfSearch.setText("");
    }//GEN-LAST:event_jbtClearDeleteActionPerformed

    private void jbtClearUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtClearUpdateActionPerformed
        // TODO add your handling code here:
        try {
            jltSearchedBook.clearSelection();
            jtfSearchUpdate.setText("");
            jcbSearchUpdate.setSelectedIndex(1);
            arrUpdateBook = null;
            arrUpdateList.clear();
            updateBookModel.removeAllElements();
            jltSearchedBook.setModel(updateBookModel);
            jtfRentPriceUpdate.setText("");
            jtfQuantityUpdate.setText("");
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "ArrayIndexOutOfBoundsException: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "NullPointerException: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtClearUpdateActionPerformed

    private void jlbLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbLogoutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_jlbLogoutMouseClicked

    private void jlbLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbLogoutMouseEntered
        // TODO add your handling code here:
        jlbLogout.setFont(new Font("Arial", Font.BOLD, 14));
        jlbLogout.setForeground(Color.red);
    }//GEN-LAST:event_jlbLogoutMouseEntered

    private void jlbLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbLogoutMouseExited
        // TODO add your handling code here:
        jlbLogout.setFont(new Font("Arial", Font.BOLD, 14));
        jlbLogout.setForeground(new Color(51, 153, 0));
    }//GEN-LAST:event_jlbLogoutMouseExited

    private void jbtViewReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtViewReportMouseClicked
        // TODO add your handling code here:
        if (jrbSalesReport.isSelected()) {
            new RentReport(admin, Integer.parseInt(String.valueOf(jcbYear.getSelectedItem()))).setVisible(true);
            this.dispose();
        } else if (jrbBookReport.isSelected()) {
            String reportSource = String.valueOf(this.getClass().getResource("Reports/")).substring(6).replaceAll("%20", " ");
            Map<String, String> params = new HashMap<String, String>();
            try {
                JasperReport jasperReport = JasperCompileManager.compileReport(reportSource + "BookReport.jrxml");
                JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params, db.getConnection());
                JasperViewer.viewReport(jasperPrint, false);
            } catch (JRException jrex) {
                JOptionPane.showMessageDialog(null, jrex.getMessage() + "Error in generating report!");
                jrex.printStackTrace();
            }
            catch (StringIndexOutOfBoundsException e) {
                JOptionPane.showMessageDialog(null, e.getMessage() + "Error in generating report!");
                e.printStackTrace();
            }catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage() + "Unable to generate report!");
            }
        } else if (jrbTotalRentReport.isSelected()) {
            String reportSource = String.valueOf(this.getClass().getResource("Reports/")).substring(6).replaceAll("%20", " ");
            Map<String, String> params = new HashMap<String, String>();
            try {
                JasperReport jasperReport = JasperCompileManager.compileReport(reportSource + "TotalRentReport.jrxml");
                JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params, db.getConnection());
                JasperViewer.viewReport(jasperPrint, false);
            } catch (JRException jrex) {
                JOptionPane.showMessageDialog(null, jrex.getMessage() + "Error in generating report!");
                jrex.printStackTrace();
            }catch (StringIndexOutOfBoundsException e) {
                JOptionPane.showMessageDialog(null, e.getMessage() + "Error in generating report!");
                e.printStackTrace();
            
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage() + "Unable to generate report!");
            }
        }
    }//GEN-LAST:event_jbtViewReportMouseClicked

    private void jltSearchedBookValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jltSearchedBookValueChanged
        // TODO add your handling code here:
        if (!jltSearchedBook.isSelectionEmpty()) {
            jtfRentPriceUpdate.setText(arrUpdateBook.get(jltSearchedBook.getSelectedIndex()).getRentPrice() + "");
            jtfQuantityUpdate.setText(arrUpdateBook.get(jltSearchedBook.getSelectedIndex()).getQuantity() + "");
        }
    }//GEN-LAST:event_jltSearchedBookValueChanged

    private void jrbRetrievePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbRetrievePasswordActionPerformed
        // TODO add your handling code here:
        if (jrbRetrievePassword.isSelected()) {
            jlbPosition.setEnabled(false);
            jlbSalary.setEnabled(false);
            jcbPosition.setEnabled(false);
            jtfSalary.setEnabled(false);
            jlbPassword.setEnabled(true);
            jbtRetrieve.setEnabled(true);
            jbtUpdateStaffStatus.setEnabled(false);
        } else {
            jlbPosition.setEnabled(true);
            jlbSalary.setEnabled(true);
            jcbPosition.setEnabled(true);
            jtfSalary.setEnabled(true);
            jlbPassword.setEnabled(false);
            jbtRetrieve.setEnabled(false);
            jbtUpdateStaffStatus.setEnabled(true);
        }
    }//GEN-LAST:event_jrbRetrievePasswordActionPerformed

    private void jbtRetrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRetrieveActionPerformed
        // TODO add your handling code here:
        if (jtfStaffID.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter staff ID!", "No Staff ID", JOptionPane.PLAIN_MESSAGE);
        } else {
            String pw = db.retrieveStaffPassword(jtfStaffID.getText());
            if (pw.equals("")) {
                JOptionPane.showMessageDialog(null, "Invalid Staff ID!", "Wrong ID", JOptionPane.ERROR_MESSAGE);
            } else {
                jtfPassword.setText(pw);
            }
        }
    }//GEN-LAST:event_jbtRetrieveActionPerformed

    private void jbtUpdateStaffStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUpdateStaffStatusActionPerformed
        // TODO add your handling code here:
        if (jtfStaffID.getText().equals("") || jtfSalary.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Incomplete informatin", "Incomplete", JOptionPane.PLAIN_MESSAGE);
        } else {
            try {
                int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to edit?", "Confirm?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (x == JOptionPane.YES_OPTION) {
                    double salary = Double.parseDouble(jtfSalary.getText());
                    db.changeStaffStatus(jtfStaffID.getText(), String.valueOf(jcbPosition.getSelectedItem()), salary);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Salary should only contain digit!", "ERROR", JOptionPane.ERROR_MESSAGE);
                new LogFile().exceptionRecord(e.getStackTrace());
            }
        }
    }//GEN-LAST:event_jbtUpdateStaffStatusActionPerformed

    private void jlbNewStaffRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNewStaffRegisterMouseClicked
        // TODO add your handling code here:
        new StaffRegisterPage(admin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlbNewStaffRegisterMouseClicked

    private void jlbNewStaffRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNewStaffRegisterMouseEntered
        // TODO add your handling code here:

        jlbLogout.setFont(new Font("Arial", Font.BOLD, 14));
        jlbLogout.setForeground(Color.red);
    }//GEN-LAST:event_jlbNewStaffRegisterMouseEntered

    private void jlbNewStaffRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNewStaffRegisterMouseExited
        // TODO add your handling code here:
        jlbLogout.setFont(new Font("Arial", Font.BOLD, 14));
        jlbLogout.setForeground(new Color(51, 153, 0));
    }//GEN-LAST:event_jlbNewStaffRegisterMouseExited

    private void jrbEditStaffStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jrbEditStaffStateChanged
        // TODO add your handling code here:
        if (!jrbEditStaff.isSelected()) {
            jlbPosition.setEnabled(false);
            jlbSalary.setEnabled(false);
            jcbPosition.setEnabled(false);
            jtfSalary.setEnabled(false);
            jlbPassword.setEnabled(true);
            jbtRetrieve.setEnabled(true);
            jbtUpdateStaffStatus.setEnabled(false);
        } else {
            jlbPosition.setEnabled(true);
            jlbSalary.setEnabled(true);
            jcbPosition.setEnabled(true);
            jtfSalary.setEnabled(true);
            jlbPassword.setEnabled(false);
            jbtRetrieve.setEnabled(false);
            jbtUpdateStaffStatus.setEnabled(true);
        }
    }//GEN-LAST:event_jrbEditStaffStateChanged

    private void jrbSalesReportStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jrbSalesReportStateChanged
        // TODO add your handling code here:
        if (jrbSalesReport.isSelected()) {
            jLabel13.setEnabled(true);
            jcbYear.setEnabled(true);
        } else {
            jLabel13.setEnabled(false);
            jcbYear.setEnabled(false);
        }
    }//GEN-LAST:event_jrbSalesReportStateChanged

    private void setBackground() {
        java.net.URL url = this.getClass().getResource("images/SMD_Library_Background.jpg");
        ImageIcon imageBack = new ImageIcon(url);
        JLabel jlbBackground = new JLabel(imageBack);
        jlbBackground.setBounds(0, 0, imageBack.getIconWidth(), imageBack.getIconHeight());
        getLayeredPane().add(jlbBackground, new Integer(Integer.MIN_VALUE));
        jpnOuter.setOpaque(false);
        setContentPane(jpnOuter);
    }

    private String getYear() {
        DateFormat dateFormat = new SimpleDateFormat("yyyy");
        return dateFormat.format(new Date());
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupReport;
    private javax.swing.ButtonGroup buttonGroupStaff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtClearDelete;
    private javax.swing.JButton jbtClearInsert;
    private javax.swing.JButton jbtClearUpdate;
    private javax.swing.JButton jbtDelete;
    private javax.swing.JButton jbtInsert;
    private javax.swing.JButton jbtRetrieve;
    private javax.swing.JButton jbtSearch;
    private javax.swing.JButton jbtSearchUpdate;
    private javax.swing.JButton jbtUpdate;
    private javax.swing.JButton jbtUpdateStaffStatus;
    private javax.swing.JButton jbtViewReport;
    private javax.swing.JComboBox jcbPosition;
    private javax.swing.JComboBox jcbSearch;
    private javax.swing.JComboBox jcbSearchUpdate;
    private javax.swing.JComboBox jcbType;
    private javax.swing.JComboBox jcbYear;
    private javax.swing.JLabel jlbLogout;
    private javax.swing.JLabel jlbNewStaffRegister;
    private javax.swing.JLabel jlbPassword;
    private javax.swing.JLabel jlbPosition;
    private javax.swing.JLabel jlbSalary;
    private javax.swing.JLabel jlbSearch;
    private javax.swing.JLabel jlbSearch1;
    private javax.swing.JLabel jlbStaffID;
    private javax.swing.JLabel jlbWelcome;
    private javax.swing.JList jltSearchResult;
    private javax.swing.JList jltSearchedBook;
    private javax.swing.JPanel jpnDelete;
    private javax.swing.JPanel jpnInsert;
    private javax.swing.JPanel jpnOuter;
    private javax.swing.JPanel jpnStaff;
    private javax.swing.JPanel jpnUpdate;
    private javax.swing.JRadioButton jrbBookReport;
    private javax.swing.JRadioButton jrbEditStaff;
    private javax.swing.JRadioButton jrbRetrievePassword;
    private javax.swing.JRadioButton jrbSalesReport;
    private javax.swing.JRadioButton jrbTotalRentReport;
    private javax.swing.JTextArea jtaDescription;
    private javax.swing.JTabbedPane jtbAdmin;
    private javax.swing.JTextField jtfAuthor;
    private javax.swing.JTextField jtfISBN;
    private javax.swing.JTextField jtfPassword;
    private javax.swing.JTextField jtfPublisher;
    private javax.swing.JTextField jtfQuantity;
    private javax.swing.JTextField jtfQuantityUpdate;
    private javax.swing.JTextField jtfRentPrice;
    private javax.swing.JTextField jtfRentPriceUpdate;
    private javax.swing.JTextField jtfSalary;
    private javax.swing.JTextField jtfSearch;
    private javax.swing.JTextField jtfSearchUpdate;
    private javax.swing.JTextField jtfStaffID;
    private javax.swing.JTextField jtfTitle;
    // End of variables declaration//GEN-END:variables
}
